- hosts: #BARTERING nodes
  gather_facts: no
  vars: 
    bootstrap_ip: "{{lookup('file','bartering-protocol/bootstrap_ip.txt')}}"
    group_name: 
  tasks:
    - name: Make bartering folder
      shell : mkdir -p bartering/{{ hostvars[inventory_hostname]['label'] }}
    - name: Copy bartering binary
      copy:
        src: bartering-protocol/bartering
        dest: bartering/{{ hostvars[inventory_hostname]['label'] }}
    - name: Copy bartering config file
      copy:
        src: bartering-protocol/{{ group_name }}/conf.yaml
        dest: bartering/{{ hostvars[inventory_hostname]['label'] }}
    - name : Authorize execution of bartering binary
      shell: chmod u+x bartering/{{ hostvars[inventory_hostname]['label'] }}/bartering
    - name: Run bartering protocol
      shell: nohup bartering/{{ hostvars[inventory_hostname]['label'] }}/bartering {{ bootstrap_ip }} &